import ScrollTopBtn from "@/components/common/ScrollTopBtn";
import "./globals.css";
import ScrollProviderWrapper from "@/components/common/ScrollProviderWrapper";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <ScrollProviderWrapper>
          {children}
          <ScrollTopBtn />
        </ScrollProviderWrapper>
        <Toaster />
      </body>
    </html>
  );
}
